# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'untitled2.ui'
# Created by: PyQt5 UI code generator 5.14.1
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets  # 确保正确导入 QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1854, 1026)
        self.zd4 = QtWidgets.QListView(Dialog)
        self.zd4.setGeometry(QtCore.QRect(-10, 0, 2021, 1061))
        self.zd4.setObjectName("zd4")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(Dialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(870, 0, 194, 26))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(940, 850, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 850, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.zd3 = QtWidgets.QListView(Dialog)
        self.zd3.setGeometry(QtCore.QRect(880, 510, 441, 331))
        self.zd3.setObjectName("zd3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 270, 1521, 661))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("QQ图片20230803224628.jpg"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(570, 110, 201, 221))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("12.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(1090, 120, 201, 211))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("13.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(1590, 110, 261, 211))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("14.png"))
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 120, 341, 201))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("15.png"))
        self.label_2.setObjectName("label_2")
        self.room1 = QtWidgets.QCommandLinkButton(Dialog)
        self.room1.setGeometry(QtCore.QRect(50, 320, 177, 41))
        self.room1.setObjectName("room1")
        self.room2 = QtWidgets.QCommandLinkButton(Dialog)
        self.room2.setGeometry(QtCore.QRect(570, 320, 177, 41))
        self.room2.setObjectName("room2")
        self.r00m3 = QtWidgets.QCommandLinkButton(Dialog)
        self.r00m3.setGeometry(QtCore.QRect(1090, 330, 177, 41))
        self.r00m3.setObjectName("r00m3")
        self.room4 = QtWidgets.QCommandLinkButton(Dialog)
        self.room4.setGeometry(QtCore.QRect(1590, 320, 177, 41))
        self.room4.setObjectName("room4")
        
        # 修改 show 为 list_view
        self.list_view = QtWidgets.QListView(Dialog)
        self.list_view.setGeometry(QtCore.QRect(1370, 390, 451, 401))
        self.list_view.setObjectName("list_view")

        # raise_方法的调用顺序
        self.zd3.raise_()
        self.zd4.raise_()
        self.label.raise_()
        self.dateTimeEdit.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.room1.raise_()
        self.room2.raise_()
        self.r00m3.raise_()
        self.room4.raise_()
        self.list_view.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "execute"))
        self.pushButton_2.setText(_translate("Dialog", "cancel"))
        self.room1.setText(_translate("Dialog", "select 1"))
        self.room2.setText(_translate("Dialog", "select2"))
        self.r00m3.setText(_translate("Dialog", "select3"))
        self.room4.setText(_translate("Dialog", "select4"))

